### ISSUE TITLE
Spectrogram.DFT()  raise ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by huangtlroom** [KinWaiCheuk/nnAudio#103]
![Screen Shot](https://imgur.com/W0xM0g2)

**Comment by KinWaiCheuk** [comment]
Hi @huangtlroom, `DFT()` has not been maintained for a while due to overlapping functionality with `STFT()`. I am planing to remove `DFT()` in my future releases.

If you set the `n_fft` for `STFT()` to be exactly the same as your signal length, and use `center=False`, it is equivalent to a DFT.
So you might want to use STFT instead.

**Comment by huangtlroom** [comment]
Thank you so much!
