### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by migperfer** [KinWaiCheuk/nnAudio#106]
Hi! I use this package a lot and I think it can be improved for further contributions:

1. All transformations are inside `Spectrogram.py`, but as the number of transformations grows up I think this is a little bit unsustainable. May we establish some categories (STFT, CQT, Mel-related, etc) so it is easier to maintain this? We can then import the models from `Spectrogram.py`
2. `Spectrogram.py` is not a very standard python name for a package, as it starts with uppercase. Changing it to lowercase would make sense? It would break the imports of packages relying on the actual version, but it looks more "pythonic" to me. Maybe we can have both and prompt deprecation warning when importing with the uppercase.
3. Tests are as well in a single file. Would it be possible to split into multiple files?

I want to work on those changes, but it would be nice to reach an agreement on how to structure it before doing a PR 😄

**Comment by gudgud96** [comment]
Hi @migperfer,  splitting the tests into different files is, of course, more modular and maintainable for future.
We can split the test files based on the categories proposed as well (but actually as of now, we don't really have that many categories to cover, which is why in the past we did not really separate them).

Overall I welcome the idea a lot! Refactoring can make the codebase more readable as well.

**Comment by KinWaiCheuk** [comment]
@migperfer Thanks so much for making this massive update. I have uploaded it to [pypi](https://pypi.org/project/nnAudio/) and updated the [documentation](https://kinwaicheuk.github.io/nnAudio/master/index.html)
