### ISSUE TITLE
Improve audio quality of Griffin-Lim implementation

### ISSUE THREAD

**Issue by gudgud96** [KinWaiCheuk/nnAudio#41]
**What should be added / fixed / improved?**

-  The current [Griffin-Lim](https://github.com/KinWaiCheuk/nnAudio/blob/master/Installation/nnAudio/Spectrogram.py#L621) implementation results in audio output with a lot of noise and burst, as compared to librosa's implementation, even though using the same number of iterations for optimization.

- "optim" module is not imported for Griffin-Lim (see [here](https://github.com/KinWaiCheuk/nnAudio/blob/master/Installation/nnAudio/Spectrogram.py#L630))

- The [test cases](https://github.com/KinWaiCheuk/nnAudio/blob/master/Installation/tests/test_spectrogram.py) should enable GPU execution.

**Comment by KinWaiCheuk** [comment]
I have been testing on Griffin-Lim and finally realized that the gradient descent is the source of problem.
Now I have changed it to a rule-based update approach based on fast Griffin-Lim to update the phases, the result is much better now. (See pull request [#59](https://github.com/KinWaiCheuk/nnAudio/pull/59/files))

Gradient descent is at least two times slower than the rule-based method and the local minimum that it reaches is not as good as the rule-based method, which causes a lot of artifacts in the reconstructed audio.

Here are the audio samples (sine wave with 440Hz) reconstructed by our implementation using rule-based, gradient descent approaches and the librosa benchmark.
[Archive.zip](https://github.com/KinWaiCheuk/nnAudio/files/5455835/Archive.zip)

In my next commit, I will update our iSTFT (actually we should use overlap add algorithm instead of that cut and stitch method that we came up last time) and separate Griffin-Lim from the STFT class.
