### ISSUE TITLE
STFT.inverse() fails on magnitude spectrograms when called multiple times

### ISSUE THREAD

**Issue by tasercake** [KinWaiCheuk/nnAudio#52]
Using `v0.1.4a0`

I came across this when calling `STFT.inverse()` more than once without calling `STFT.forward(..., output_format="Magnitude")` in between.

### Minimal code sample

```python
from nnAudio import Spectrogram
from scipy.io import wavfile
import torch

# Get an STFT magnitude spectrogram
audio = torch.tensor(wavfile.read("song.wav")).float()
to_stft = Spectrogram.STFT()
stft = to_stft(audio, output_format="Magnitude")

# Reconstruct audio from STFT
reconstructed = to_stft.inverse(stft)

# Reconstruct audio from STFT (again)
reconstructed = to_stft.inverse(stft)   # AssertionError: Only perform inverse function on Magnitude or Complex spectrogram.
```

It looks like the issue is caused by an [internal call](https://github.com/KinWaiCheuk/nnAudio/blob/800aba5731fab2911a105181eb3bc744d6ae2519/Installation/nnAudio/Spectrogram.py#L685) to `self.forward(..., output_format="Complex")` within `STFT.inverse()`.

### Workaround

Explicitly set the output format before calling `inverse()`
```python
to_stft.output_format = "Magnitude"
reconstructed = to_stft.inverse(stft)
```

### Fix?

Perhaps making `STFT()` similar to `CQT2010v2()` and [specifying the output format at instantiation](https://github.com/KinWaiCheuk/nnAudio/blob/800aba5731fab2911a105181eb3bc744d6ae2519/Installation/nnAudio/Spectrogram.py#L1549):
```python
class STFT(nn.Module):
    def __init__(self, ..., output_format="Complex"):
        self.output_format = output_format
        ...
```

Unless there's a particular reason for setting `self.output_format` in `STFT.forward()`, it's probably more intuitive to set a default `self.output_format` in `STFT.__init__()`.
For the sake of backward compatibility, the `output_format` param of `STFT.forward()` could be retained to override the default value without changing the module's state.

**Comment by KinWaiCheuk** [comment]
Hi tasercake, thanks for pointing out this problem and providing a possible fix.
The reason for having the `self.output_format` in `STFT.forward()` is that Griffin-Lim (another inverse function inside STFT) requires the complex output.
But you are right, we should figure out a way to avoid this bug while allowing Griffin-Lim to work. 

Since this fix will also affect Griffin-Lim, I think I need more time later to investigate.
Alternatively, would you like to make a pull request? So that I can just check your fix to see if it works for Griffin-Lim too.

I will post the instruction on how to do unit test if you are interested in doing a pull request.

**Comment by tasercake** [comment]
I've created a PR with the changes I made on my end (though I haven't changed/added any tests yet)

At least in my specific use case of inverting a magnitude spectrogram via Griffin-Lim, these changes didn't seem to cause any issues
