### ISSUE TITLE
torch.rfft has been moved

### ISSUE THREAD

**Issue by THasthika** [KinWaiCheuk/nnAudio#98]
`torch.rfft` should be ported to `torch.fft.rfft`

https://github.com/KinWaiCheuk/nnAudio/blob/bf7a6392b32f11294d677cba1920886f5b321730/Installation/nnAudio/Spectrogram.py#L566

https://github.com/KinWaiCheuk/nnAudio/blob/bf7a6392b32f11294d677cba1920886f5b321730/Installation/nnAudio/Spectrogram.py#L2254

https://github.com/KinWaiCheuk/nnAudio/blob/bf7a6392b32f11294d677cba1920886f5b321730/Installation/nnAudio/Spectrogram.py#L2257

https://github.com/KinWaiCheuk/nnAudio/blob/bf7a6392b32f11294d677cba1920886f5b321730/Installation/nnAudio/Spectrogram.py#L2443

**Comment by KinWaiCheuk** [comment]
Hi THasthika, thanks for pointing it out! Indeed torch.rfft is not longer available since PyTorch 1.8. But it is better to keep the support for older versions, since torch.fft.rfft is not available before version 1.7.

One solution I can think of is to import `rfft` functions differently based on the PyTorch version the user is using. Something similar to this [stackoverflow post](https://stackoverflow.com/questions/1875259/importing-a-module-based-on-installed-python-version).

In our case it would be like 
```python
if torch.__version__<1.7:
    import torch.rfft as rfft
else:
    import torch.fft.rfft as rfft
```

Then in the main code, we replace `torch.rfft` by `rfft`.

Would you like to make a pull request? I am a little busy recently, so it might took me a while to check and do it myself.

**Comment by THasthika** [comment]
@KinWaiCheuk It was not as simple as that since PyTorch has adopted the Complex data type for fft functions. I had to use the `torch.fft.fft` to compute the equivalent in the newer versions. I've created a simple helper function `rfft_fn` to determine the function to run.

**Comment by KinWaiCheuk** [comment]
Thanks for the quick pull request! The workflow you added is really helpful too.
